### ISSUE TITLE
There is a Bug with images. They get to big

### ISSUE THREAD

**Issue by noam2** [Nightonke/BoomMenu#93]
i looked at the sample app code, and your image drawables are 128x128. 
you didn't use in builder any method , like new Rect or anything else, and it looks good in all the samples and screens. 
but when i tried to put smaller images (70 x 70), without using any method as well, they get bigger automatically, i did various tries and options. i think u need to fix it.

**Comment by Nightonke** [comment]
That's not a bug. My images look well with 128*128 size because the padding in the images. Just like the image below(It's too white to see):
![](https://github.com/Nightonke/BoomMenu/blob/master/app/src/main/res/drawable/bat.png?raw=true)

And you can use `imageRect` or `imagePadding` methods of builder to adjust your images.
